apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-creator
  namespace: podtinytidyid-webhook
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-creator-binding
  namespace: podtinytidyid-webhook
subjects:
- kind: ServiceAccount
  name: default
  namespace: podtinytidyid-webhook
roleRef:
  kind: Role
  name: configmap-creator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-pods-everywhere
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-pods-everywhere-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: podtinytidyid-webhook
roleRef:
  kind: ClusterRole
  name: get-pods-everywhere
  apiGroup: rbac.authorization.k8s.io




  
